[project]
name = "image-composition-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pacotiber", email = "pacotiber@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
image-composition-engine = "image_composition_engine:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
